### ISSUE TITLE
Feature Request: Other donation methods

### ISSUE THREAD

**Issue by BenjaminListwon** [matthewgonzalez/fontplop#11]
Hey fellas,

I came here via Jeremiah's Typewolf newsletter ( https://www.typewolf.com/ ) and I want to make you rich for your contribution to the world. Sadly, I don't do the bitcoin jam, and I'm guessing there may be other less-cryptocurrrency-inclined folks out there that are in the same boat. 

Help us hopelessly backward-thinking Luddites throw our money your way with Patreon or Stripe or some other service that transmogrifies cash dollars into bits?

--Ben

**Comment by matthewgonzalez** [comment]
Thanks @BenjaminListwon. You're awesome! 

I set up an OpenCollective page for this project: https://opencollective.com/fontplop
