### ISSUE TITLE
JS error occurred in main process

### ISSUE THREAD

**Issue by tiffting** [matthewgonzalez/fontplop#18]
I dragged some OTF files into the fontplop window, but I'm not sure what is causing this error:
<img width="504" alt="screen shot 2017-11-26 at 5 35 11 pm" src="https://user-images.githubusercontent.com/531003/33238820-e871a922-d25a-11e7-9422-d9456d0aaaa7.png">

**Comment by briangonzalez** [comment]
@tiffting Would you be willing to send the files you were attempting to convert to me@briangonzalez.org? I'll dig in and see what's going on.

**Comment by lifeinchords** [comment]
Hi Brian, 
This is an awesome project... 

I'm having the same error as @tiffting with many typefaces from different origins.

An example, from a free + open source typeface:
[Inter-UI-BlackItalic.otf.zip](https://github.com/matthewgonzalez/fontplop/files/1504040/Inter-UI-BlackItalic.otf.zip)
From: https://rsms.me/inter/
