### ISSUE TITLE
Erroneous version notification

### ISSUE THREAD

**Issue by lunelson** [matthewgonzalez/fontplop#21]
tells me about version 1.3.0 when I already have 1.3.0

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1242864/33310476-0871453e-d422-11e7-8dbb-150b175ac76a.png">

**Comment by briangonzalez** [comment]
@lunelson Does this happen every time you open the app?

**Comment by lunelson** [comment]
No, it happened again just now but I hit escape and when I relaunched it wasn't there. Cached value in prefs or something?

**Comment by briangonzalez** [comment]
@matthewgonzalez Any ideas? Not happening for me.

**Comment by matthewgonzalez** [comment]
I'm not sure, I'll take a look and let y'all know.

**Comment by briangonzalez** [comment]
Going to close for now. Let's reopen when we have something more actionable.
